# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'sample-integration-ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for sample-integration-ios
  pod 'NatDS'

  target 'sample-integration-iosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'sample-integration-iosUITests' do
    # Pods for testing
  end

end
