require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'
use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

def react_native_dependencies
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])
end

target 'sample-integration-ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for sample-integration-ios
  pod 'NatDS'
  react_native_dependencies

  target 'sample-integration-iosTests' do
    inherit! :search_paths
    # Pods for testing
    react_native_dependencies
  end

  target 'sample-integration-iosUITests' do
    # Pods for testing
    react_native_dependencies
  end

end
