require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'
use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

def react_native_dependencies
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])
  pod "rn-sample-ios-lib", :git => "git@github.com:natura-cosmeticos/natds-rn-samples.git", :branch => "ios-integration"
  pod "rn-sample-fixed-ios-lib", :git => "git@github.com:natura-cosmeticos/natds-rn-samples.git", :branch => "ios-integration"
end

target 'sample-integration-ios' do
  # Pods for sample-integration-ios
  pod 'NatDS'
  react_native_dependencies

  target 'sample-integration-iosTests' do
    inherit! :search_paths
    # Pods for testing
    react_native_dependencies
  end

  target 'sample-integration-iosUITests' do
    # Pods for testing
    react_native_dependencies
  end
end
